/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/nbb0MOIMOd1
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/

import Link from 'next/link';
import Image from 'next/image';
import { Separator } from '@/components/shadcn/separator';
import { SiFacebook as FacebookIcon } from '@icons-pack/react-simple-icons';
import { SiInstagram as InstagramIcon } from '@icons-pack/react-simple-icons';

export function Footer() {
  return (
    <footer className="bg-blue-500 py-6 w-full">
      <div className="container mx-auto flex flex-col items-center gap-6">
        <div className="flex items-center gap-3 justify-center">
          <Image src="/img/club_logo.webp" alt={'logo'} width={40} height={40} />
          <span className="text-primary-foreground text-xl font-semibold">Upprustningen Sports Club</span>
        </div>
        <Separator orientation="horizontal" decorative className="h-0.5" />
        <div className="w-full max-w-5xl flex flex-col md:flex-row md:justify-evenly md:items-center gap-6 md:gap-60">
          <section className="flex flex-col items-center md:items-start gap-2">
            <Link
              href="#"
              className="text-primary-foreground hover:text-primary transition-colors"
              prefetch={false}
            >
              Hem
            </Link>
            <Link
              href="#"
              className="text-primary-foreground hover:text-primary transition-colors"
              prefetch={false}
            >
              Om oss
            </Link>
            <Link
              href="#"
              className="text-primary-foreground hover:text-primary transition-colors"
              prefetch={false}
            >
              Kontakt
            </Link>
            <Link
              href="#"
              className="text-primary-foreground hover:text-primary transition-colors"
              prefetch={false}
            >
              Schema
            </Link>
          </section>
        </div>
        <section className="flex flex-col items-center md:items-start">
          <span className="text-primary-foreground font-semibold">Kontakt</span>
          <span className="text-primary-foreground" aria-label="email adress information">
            info@upprustningen.com
          </span>
        </section>
        <section
          className="flex justify-center md:justify-start items-center gap-6"
          aria-label="social media icons"
        >
          <Link
            href="#"
            aria-label="Facebook icon"
            className="text-primary-foreground transition-colors"
            prefetch={false}
          >
            <FacebookIcon size={28} />
          </Link>
          <Link
            href="https://www.instagram.com/totalsthlm/?igshid=MzRlODBiNWFlZA%3D%3D"
            aria-label="Instagram icon"
            className="text-primary-foreground transition-colors"
            prefetch={false}
          >
            <InstagramIcon size={28} />
          </Link>
        </section>
        <div className="flex justify-center mt-6">
          <p className="text-primary-foreground text-xs">
            &copy; 2024 Upprustningen Sports Club. All rights reserved.
          </p>
        </div>
      </div>
    </footer>
  );
}
