// /**
//  * This code was generated by v0 by Vercel.
//  * @see https://v0.dev/t/nbb0MOIMOd1
//  * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
//  */

// import Link from 'next/link';
// import Image from 'next/image';

// export function Footer() {
//   return (
//     <footer className="bg-muted py-12 w-full">
//       <div className="container mx-auto flex flex-col md:flex-row md:justify-between md:items-center gap-6 md:gap-0">
//         <div className="flex justify-center md:justify-start items-center gap-4">
//           <Link
//             href="#"
//             aria-label="Twitter"
//             className="text-muted-foreground hover:text-primary transition-colors"
//             prefetch={false}
//           ></Link>
//           <Link
//             href="#"
//             aria-label="LinkedIn"
//             className="text-muted-foreground hover:text-primary transition-colors"
//             prefetch={false}
//           >
//             <LinkedinIcon className="h-6 w-6" />
//           </Link>
//           <Link
//             href="#"
//             aria-label="Instagram"
//             className="text-muted-foreground hover:text-primary transition-colors"
//             prefetch={false}
//           >
//             <InstagramIcon className="h-6 w-6" />
//           </Link>
//         </div>
//         <div className="flex justify-center items-center gap-3">
//           <Image src="/img/club_logo.webp" alt={'logo'} width={40} height={40} />
//           <span className="text-xl font-semibold">Upprustningen Sports Club</span>
//         </div>
//         <div className="flex flex-col items-center md:items-start gap-2">
//           <Link
//             href="/"
//             className="text-muted-foreground hover:text-primary transition-colors"
//             prefetch={false}
//           >
//             Hem
//           </Link>
//           <Link
//             href="/om-oss"
//             className="text-muted-foreground hover:text-primary transition-colors"
//             prefetch={false}
//           >
//             Om oss
//           </Link>
//           <Link
//             href="/bli-medlem"
//             className="text-muted-foreground hover:text-primary transition-colors"
//             prefetch={false}
//           >
//             Registrera dig
//           </Link>
//           <Link
//             href="/kontakta-oss"
//             className="text-muted-foreground hover:text-primary transition-colors"
//             prefetch={false}
//           >
//             Kontakta oss
//           </Link>
//           <Link
//             href="/schema"
//             className="text-muted-foreground hover:text-primary transition-colors"
//             prefetch={false}
//           >
//             Schema
//           </Link>
//         </div>
//         <div className="flex justify-center mt-6 md:mt-0">
//           <p className="text-xs text-muted-foreground">
//             &copy; 2024 Upprustningen Sports Club. All rights reserved.
//           </p>
//         </div>
//       </div>
//     </footer>
//   );
// }

// function InstagramIcon(props: any) {
//   return (
//     <svg
//       {...props}
//       xmlns="http://www.w3.org/2000/svg"
//       width="24"
//       height="24"
//       viewBox="0 0 24 24"
//       fill="none"
//       stroke="currentColor"
//       strokeWidth="2"
//       strokeLinecap="round"
//       strokeLinejoin="round"
//     >
//       <rect width="20" height="20" x="2" y="2" rx="5" ry="5" />
//       <path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z" />
//       <line x1="17.5" x2="17.51" y1="6.5" y2="6.5" />
//     </svg>
//   );
// }

// function LinkedinIcon(props: any) {
//   return (
//     <svg
//       {...props}
//       xmlns="http://www.w3.org/2000/svg"
//       width="24"
//       height="24"
//       viewBox="0 0 24 24"
//       fill="none"
//       stroke="currentColor"
//       strokeWidth="2"
//       strokeLinecap="round"
//       strokeLinejoin="round"
//     >
//       <path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z" />
//       <rect width="4" height="12" x="2" y="9" />
//       <circle cx="4" cy="4" r="2" />
//     </svg>
//   );
// }

// function TwitterIcon(props: any) {
//   return (
//     <svg
//       {...props}
//       xmlns="http://www.w3.org/2000/svg"
//       width="24"
//       height="24"
//       viewBox="0 0 24 24"
//       fill="none"
//       stroke="currentColor"
//       strokeWidth="2"
//       strokeLinecap="round"
//       strokeLinejoin="round"
//     >
//       <path d="M22 4s-.7 2.1-2 3.4c1.6 10-9.4 17.3-18 11.6 2.2.1 4.4-.6 6-2C3 15.5.5 9.6 3 5c2.2 2.6 5.6 4.1 9 4-.9-4.2 4-6.6 7-3.8 1.1 0 3-1.2 3-1.2z" />
//     </svg>
//   );
// }
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/nbb0MOIMOd1
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Instagram } from 'lucide-react';
import { Icon } from 'next/dist/lib/metadata/types/metadata-types';
import Link from 'next/link';
import Image from 'next/image';

export function Footer() {
  return (
    <footer className="bg-muted py-12 w-full">
      <div className="container mx-auto flex flex-col items-center gap-6">
        <div className="flex items-center gap-3 justify-center">
          <Image src="/img/club_logo.webp" alt={'logo'} width={40} height={40} />
          <span className="text-xl font-semibold">Upprustningen Sports Club</span>
        </div>
        <div className="border-b w-full max-w-5xl mb-6"></div>
        <div className="w-full max-w-5xl flex flex-col md:flex-row md:justify-between md:items-center gap-6 md:gap-0">
          <div className="flex justify-center md:justify-start items-center gap-4">
            <Link
              href="#"
              aria-label="Twitter"
              className="text-muted-foreground hover:text-primary transition-colors"
              prefetch={false}
            >
              <TwitterIcon className="h-6 w-6" />
            </Link>
            <Link
              href="#"
              aria-label="LinkedIn"
              className="text-muted-foreground hover:text-primary transition-colors"
              prefetch={false}
            >
              <LinkedinIcon className="h-6 w-6" />
            </Link>
            <Link
              href="#"
              aria-label="Instagram"
              className="text-muted-foreground hover:text-primary transition-colors"
              prefetch={false}
            >
              <InstagramIcon className="h-6 w-6" />
            </Link>
          </div>
          <div className="flex flex-col items-center md:items-start gap-2">
            <Link
              href="#"
              className="text-muted-foreground hover:text-primary transition-colors"
              prefetch={false}
            >
              Hem
            </Link>
            <Link
              href="#"
              className="text-muted-foreground hover:text-primary transition-colors"
              prefetch={false}
            >
              Om oss
            </Link>
            <Link
              href="#"
              className="text-muted-foreground hover:text-primary transition-colors"
              prefetch={false}
            >
              Kontakt
            </Link>
            <Link
              href="#"
              className="text-muted-foreground hover:text-primary transition-colors"
              prefetch={false}
            >
              Schema
            </Link>
          </div>
        </div>
        <div className="flex justify-center mt-6">
          <p className="text-xs text-muted-foreground">
            &copy; 2024 Upprustningen Sports Club. All rights reserved.
          </p>
        </div>
      </div>
    </footer>
  );
}

function InstagramIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="20" height="20" x="2" y="2" rx="5" ry="5" />
      <path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z" />
      <line x1="17.5" x2="17.51" y1="6.5" y2="6.5" />
    </svg>
  );
}

function LinkedinIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z" />
      <rect width="4" height="12" x="2" y="9" />
      <circle cx="4" cy="4" r="2" />
    </svg>
  );
}

function TwitterIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 4s-.7 2.1-2 3.4c1.6 10-9.4 17.3-18 11.6 2.2.1 4.4-.6 6-2C3 15.5.5 9.6 3 5c2.2 2.6 5.6 4.1 9 4-.9-4.2 4-6.6 7-3.8 1.1 0 3-1.2 3-1.2z" />
    </svg>
  );
}
